steps:
  # 1. Build the JAR file using Maven
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # 2. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'us-east1-docker.pkg.dev/gcp-training-v2/cts-repo-albin/spring-boot-app:latest', '.'
    ]

  # 3. Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-east1-docker.pkg.dev/gcp-training-v2/cts-repo-albin/spring-boot-app:latest'
    ]

  # 4. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'spring-boot-app',
      '--image', 'us-east1-docker.pkg.dev/gcp-training-v2/cts-repo-albin/spring-boot-app',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'us-east1-docker.pkg.dev/gcp-training-v2/cts-repo-albin/spring-boot-
app'